### ISSUE TITLE
[Bug Report] Vuetify cli plugin breaks mocha tests

### ISSUE THREAD

**Issue by JamesMcMahon** [vuetifyjs/vue-cli-plugin-vuetify#101]
### Environment
**Vuetify Version:** 2.0.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.100
**OS:** Mac OS 10.14.5

### Steps to reproduce
Run `yarn test:unit`

Project was generated using

`vue create vuetify-create-test`
`vue add vuetify`

#### Vue create options

Customized to add mocha tests:

<img width="401" alt="Screen Shot 2019-07-30 at 2 47 45 PM" src="https://user-images.githubusercontent.com/916676/62160319-45310a80-b2d9-11e9-8454-4d799e1b6cbb.png">

Defaults are selected for every other option

### Expected Behavior
Tests will run

### Actual Behavior
Tests break with sass compilation issue:

```
WEBPACK  Failed to compile with 4 error(s)

Error in ./node_modules/vuetify/src/components/VGrid/VGrid.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                   root stylesheet
        in http:/localhost/Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VGrid/_grid.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                   root stylesheet
        in http:/localhost/Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VImg/VImg.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                   root stylesheet
        in http:/localhost/Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)

Error in ./node_modules/vuetify/src/components/VResponsive/VResponsive.sass

  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
  Expected ";".
    ╷
  1 │ @import './settings/_index'
    │                            ^
    ╵
    Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass 1:28  @import
    stdin 1:9                                                                                   root stylesheet
        in http:/localhost/Users/james/workspace/vuetify-create-test/node_modules/vuetify/src/styles/styles.sass (line 1, column 28)
```

### Reproduction Link
<a href="https://github.com/JamesMcMahon/vuetify-create-issues" target="_blank">https://github.com/JamesMcMahon/vuetify-create-issues</a>

**Comment by nekosaur** [comment]
You can use `null-loader` with the following in `vue.config.js`

```js
  chainWebpack: config => {
    if (process.env.NODE_ENV === 'test') {
      const sassRule = config.module.rule('sass')
      sassRule.uses.clear()
      sassRule.use('null-loader').loader('null-loader')
    }
  }
```

**Comment by turdwaster** [comment]
In my case, the error is `Can't find stylesheet to import.` on the line `@import '../../styles/styles.sass'` for all components in `./node_modules/vuetify/src/components/`. I can confirm that using the null-loader from previous comment works around the issue.

**Comment by JamesMcMahon** [comment]
> You can use `null-loader` together with the following in `vue.config.js`
> 
> ```js
>   chainWebpack: config => {
>     if (process.env.NODE_ENV === 'test') {
>       const sassRule = config.module.rule('sass')
>       sassRule.uses.clear()
>       sassRule.use('null-loader').loader('null-loader')
>     }
>   }
> ```

I can confirm this works for my project. Haven't gotten a chance to try it out on the minimal example in my repo yet, but I would assume it would work as well since they were demonstrating the same issue.

**Comment by EtienneM** [comment]
This one bugged me for some time. I actually had to slightly modify the suggested solution with:

```js
  chainWebpack: (config) => {
    if (process.env.NODE_ENV === 'test') {
      const sassRule = config.module.rule('sass')
      sassRule.uses.clear()
      sassRule.use('null-loader').loader('null-loader')
      const scssRule = config.module.rule('scss')
      scssRule.uses.clear()
      scssRule.use('null-loader').loader('null-loader')
    }
    // Allow to mix SASS and SCSS
    // https://vuetifyjs.com/en/customization/sass-variables#single-file-components
    ['vue-modules', 'vue', 'normal-modules', 'normal'].forEach((match) => {
      config.module.rule('scss').oneOf(match).use('sass-loader')
        .tap(opt => Object.assign(opt, { data: '@import "~@/styles/application.scss";' }))
    })
  },
```

I think that this [documentation page](https://vuetifyjs.com/en/customization/sass-variables#single-file-components) should be updated to mention this.

Thanks a lot @nekosaur!

**Comment by JamesMcMahon** [comment]
@johnleider Thanks John!

Once this is released I can test this on my example project

**Comment by JamesMcMahon** [comment]
Testing this fix post release.

Using `vue-cli` version 3.12.0 and running the reproduction steps above I still have issues around the null loader.

```
WEBPACK  Failed to compile with 9 error(s)

Error in ./node_modules/vuetify/lib/components/VImg/VImg.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VContainer.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VLayout.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VSpacer.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VFlex.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VContainer.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VCol.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VGrid/VRow.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

Error in ./node_modules/vuetify/lib/components/VResponsive/VResponsive.js

  Module not found: 'null-loader' in '/Users/jamie/temp/vuetify-create-test'

 ERROR  mocha-webpack exited with code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by M3psipax** [comment]
I still have this issue with with vue ^2.6.11 and vue-cli-service ~4.4.0 and vue-cli-plugin-vuetify ~2.0.5.

None of the solutions provided worked for me. I had to install null-loader first. Now, I get the sass import failures.

**Comment by xiaohundun** [comment]
> I still have this issue with with vue ^2.6.11 and vue-cli-service ~4.4.0 and vue-cli-plugin-vuetify ~2.0.5.
> 
> None of the solutions provided worked for me. I had to install null-loader first. Now, I get the sass import failures.
> 
> Actually, I just realized it's not entirely the same issue since the error reads "SassError: Can't find stylesheet to import."
> 
> Edit 1: So for anyone else struggling with this, I was able to resolve it like this:
> 
> Use https://www.npmjs.com/package/ignore-styles and https://www.npmjs.com/package/ignore-loader.
> 
> Add `--require ignore-styles` to your unit test command.
> 
> Then put into your **vue.config.js**:
> 
> ```
> if (process.env.NODE_ENV === "test") {
> config.module
>         .rule("ignore-vuetify-styles")
>         .test(/\.(sass|scss)/)
>         .include.add(path.resolve(__dirname, "node_modules/vuetify"))
>         .end()
>         .use("ignore-loader")
>         .loader("ignore-loader")
>         .end();
>  }
> ```
> 
> Edit 2:
> 
> Forget all of the above!
> 
> For anyone coming across this: I still encountered some issues after configuring to ignore styles. So I did some more digging, and it turns out that my tests broke because I had in my **vue.config.js**:
> 
> ```
> css: { extract: { ignoreOrder: true}}
> ```
> 
> For some reason, this causes the ExtractCssPlugin to fail in tests, presumably because the `extract` object overwrites the base configuration completely.
> 
> So I just did:
> 
> ```
>   css:
>     process.env.NODE_ENV === "production"
>       ? {
>           extract: { ignoreOrder: true },
>         }
>       : undefined,
> ```
> 
> Now I've got everything working without any need for additional plugins or requires by simply using `vue-cli-service test:unit` as is.

saved my life!!!!thanks!!!!
