### ISSUE TITLE
[Bug Report] Build is failing - opts is undefined

### ISSUE THREAD

**Issue by SingularReza** [vuetifyjs/vue-cli-plugin-vuetify#106]
### Environment

Vuetify Version: 2.0.5
Vue Version: 2.6.10
vue-cli-plugin-vuetify: latest beta
OS: Windows subsystem for Linux

### Steps to reproduce
* `vue create test-app`
* `cd test-app`
* `vue add vuetify`
* Upgrade to the beta version like [here](https://github.com/vuetifyjs/vuetify/releases/v2.0.0-beta.0)
 The code used :   
 `$ npm install https://github.com/vuetifyjs/vue-cli-plugin-vuetify.git#dev --save-dev`  
`$ vue invoke vuetify`
* `npm run serve` or `npm run build`

### Expected behaviour
Build or compile without any error  

### Actual Behaviour  

![Screenshot (24)](https://user-images.githubusercontent.com/36134253/62810118-997a8c80-bb1a-11e9-9b90-c61097a0e50b.png)

### Temporary solution  
Add an `opts` parameter after the `api` parameter in the arrow function at line 7 of `index.js` in `vue-cli-plugin-vuetify` in `node_modules`

**Comment by KaelWD** [comment]
fa4c35e888598ab74d74b0d4d218f3af044ebc47

**Comment by droyson** [comment]
Even I'm facing the same issue on upgrading `vue-cli-plugin-vuetify` to `latest`.
Looks like the `opts` parameter was dropped in the [next commit to index.js](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/commit/4e84c857529432100482e253f88898b6158652d2#diff-168726dbe96b3ce427e7fedce31bb0bcL7).

I'm adding import to `scss` files from vue.config.js using:
```javascript
['vue-modules', 'vue', 'normal-modules', 'normal'].forEach((match) => {
      config.module.rule('scss').oneOf(match).use('sass-loader')
        .tap(opt => Object.assign(opt, { data: `@import '~@/sass/main.scss';` }))
    })
```
