### ISSUE TITLE
[Bug Report] vuetify Plugin breaks babel config

### ISSUE THREAD

**Issue by lino** [vuetifyjs/vue-cli-plugin-vuetify#107]
# Environment
Vuetify Version: 2.0.5
Vue Version: 2.6.10
vue-cli-plugin-vuetify: 0.6.3
OS: Linux

# Steps to reproduce
Or clone repo https://github.com/lino/vuetify-cli-property-issue

vue create test-app
cd test-app
add a class using a class property to main.js or another included file

    class Test {
      static prop = 'foo';
    }
yarn serve to verify that it's working
vue add vuetify
yarn serve to see that it's not working anymore

# Expected behaviour
Build or compile without any error as it does before you add vuetify plugin

# Actual Behaviour
![Screenshot_2019-08-13_15-13-47](https://user-images.githubusercontent.com/1456957/62944466-0ae96200-bddd-11e9-8f33-db5d2421f66b.png)

> Module parse failed: Unexpected token (2:13)
> You may need an appropriate loader to handle this file type.

# Temporary solutions
* Downgrade to 0.6.1
or
* Don't use class property syntax

**Comment by KaelWD** [comment]
Probably bb3ffca80d262be648fd8eeb030566dc8294619c
Does it work if you add `transpileDependencies: ['vuetify']`?

**Comment by EmeraldCoder** [comment]
I got the same problem on my project and the workaround of manually adding the `transpileDependencies` in the `vue.config.js` was working fine for me.

**Comment by MrBretticus** [comment]
Can also confirm `transpileDependencies` in `vue.config.js` works.

**Comment by randompixel** [comment]
Thanks all for this. Just spent a day wondering why `@babel/plugin-proposal-optional-chaining` wasn't compiling any more. Feels like this needs adding by default or something?

**Comment by johnleider** [comment]
This will be automatic on install as of next release.

**Comment by mikeebowen** [comment]
Thanks so much for this thread, I've been trying to figure this out all weekend!
