### ISSUE TITLE
[Bug Report] Can not install previous version of vuetify

### ISSUE THREAD

**Issue by Psik628** [vuetifyjs/vue-cli-plugin-vuetify#111]
### Environment

**Browsers:** Chrome 76.0.3809.132
**OS:** Windows 10

### Steps to reproduce
vue add vuetify@1.5.3

### Expected Behavior
Downloading vuetify

### Actual Behavior
error

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
Hi guys,
when I try to install older version of vuetify i get error 
command failed: npm install --loglevel error -D vue-cli-plugin-vuetify@1

**Comment by nekosaur** [comment]
the version that you specify when doing `vue add vuetify` will be the version of the plugin, not vuetify itself.
