### ISSUE TITLE
[Bug Report] Plugin breaks Babel transpilation

### ISSUE THREAD

**Issue by kamilzzz** [vuetifyjs/vue-cli-plugin-vuetify#113]
Environment
------
Vue CLI version: 3.11.0
OS: Windows

Steps to reproduce
------
vue create .
vue add vuetify
npm run serve

Chrome DevTools -> Source -> Select app.js -> Search for `#app`.
You will notice that arrow function in main.js is not transpiled: `render: h => h(app).`

Adding `vue.config.js` with `transpileDependencies ` doesn't help (#55).

Expected behaviour
------
Code is transpiled and app can be run on IE11.

Actual Behaviour
------
Code is not transpiled and IE11 shows blank page.

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/getting-started/quick-start#edge-support

**Comment by kamilzzz** [comment]
Adding `transpileDependencies ` to `vue.config.js` doesn't help at all.

Also the error doesn't come from Vuetify. I don't know why, but when after using `vue add vuetify` the `main.js` file is not transpiled anymore.

**Comment by jacekkarczmarczyk** [comment]
Please provide a reproduction so we have something to look at (can be boiled down github repo)

**Comment by kamilzzz** [comment]
Here is repo:
https://github.com/kamilzzz/vuetify-cli

But the only two things I did was: 
1. `vue create .`
2. `vue add vuetify`

All with default settings.

If I run `npm run serve` before adding vuetify via `vue add vuetify` I can see arrow function in main.js is transpilled correctly and app works in IE11.

After executing `vue add vuetify` arrow function in main.js is not transpilled anymore and IE11 throws error.

Am I missing something?

**Comment by jacekkarczmarczyk** [comment]
Looks duplicate/related to https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/107, can you confirm that 0.6.1 works for you?

**Comment by kamilzzz** [comment]
Works on 0.6.1.

But adding `transpileDependecies` on 0.6.3 doesn't help.

**Comment by nekosaur** [comment]
`transpileDependencies` does work

**Comment by kamilzzz** [comment]
I have tried again and it didn't work for me.

Can you fork https://github.com/kamilzzz/vuetify-cli and show me how to configure `transpileDependencies` to make it work under IE11?

I also don't understand how `transpileDependencies` might help if the error comes from `main.js` (specifically from `render` arrow function not being transpiled) and not some file related to `vuetify`.

**Comment by nekosaur** [comment]
I cloned your repo, added `vue.config.js` file with the following
```
module.exports = {
  transpileDependencies: ['vuetify']
}
```
and tested it with IE11

**Comment by kamilzzz** [comment]
Ok, this one works.

Before I tried with different regexps as pointed here: 
https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/55#issuecomment-443185444

**Comment by KaelWD** [comment]
That was changed after https://github.com/vuejs/vue-cli/issues/3057
