### ISSUE TITLE
[Feature Request] Make variables folder `styles`

### ISSUE THREAD

**Issue by MrJmpl3** [vuetifyjs/vue-cli-plugin-vuetify#116]
I have a question, why src/sass?

I think it is tidier to put it in "assets / styles"

**Comment by johnleider** [comment]
Yes agreed,  I will add this.

**Comment by phiter** [comment]
I think it would be better if this were a configurable setting on vue.config.js.

**Comment by MrJmpl3** [comment]
> 
> 
> I think it would be better if this were a configurable setting on vue.config.js.

Why not, the two options? .. Configurable settings and "assets/styles" per default

**Comment by phiter** [comment]
There should be a default setting to reduce setup cost, and that will be explicit in the documentation, for sure.
Now if the default should be `@/assets/styles`, I'm not sure.
I personally use `@/assets/scss`. @chrisvfritz [enterprise boilerplate project](https://github.com/chrisvfritz/vue-enterprise-boilerplate/tree/master/src/design) uses a design folder.
So yeah I'm not sure what should be the default.

**Comment by MrJmpl3** [comment]
`@/assets/styles` or `@/assets/scss` is same, but styles is a word "more global" ..

**Comment by johnleider** [comment]
This will be partially fulfilled as a fix for a bug in v1 will now check styles/sass/scss folders for files. For next minor I will add the ability to define a custom path.

**Comment by johnleider** [comment]
This is already in the wild. The user can use **sass**, **scss** or **styles**.
