### ISSUE TITLE
[Bug Report] release 1.0.1 Sass Loader does not match the API schema

### ISSUE THREAD

**Issue by PierreBrisorgueil** [vuetifyjs/vue-cli-plugin-vuetify#119]
hello, since last release & vue cli 4

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'data'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/pierrebrisorgueil/Documents/Dev/github/rype/Vue/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/pierrebrisorgueil/Documents/Dev/github/rype/Vue/node_modules/sass-loader/dist/index.js:36:28)

 @ ./node_modules/vuetify/src/components/VSpeedDial/VSpeedDial.sass 4:14-209 14:3-18:5 15:22-217
 @ ./node_modules/vuetify/lib/components/VSpeedDial/VSpeedDial.js
 @ ./node_modules/vuetify/lib/components/VSpeedDial/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/lib/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

- Travis informations [here](https://travis-ci.org/weareopensource/Vue/jobs/595952182)
- maybe related to https://github.com/vuejs/vue-cli/issues/4513
- tested with vue cli 4.0.0-rc.7
- repo concerned : https://github.com/weareopensource/Vue

I would take a look as soon as I have a little time, if I can help do not hesitate.

how to reproduce : 

- clone the [repo](https://github.com/weareopensource/Vue) 
- npm i
- npm start, everything would be ok
- switch     "vue-cli-plugin-vuetify": "^1.0.0" => "vue-cli-plugin-vuetify": "^1.0.1"
- npm i 
- npm start, error should appear

**Comment by claudio10** [comment]
there have been reports of vue-cli 4 not working with sass-loader version 8.0.0. do you have it installed in your project? Try downgrading to sass-loader@7.3.1 should work.

**Comment by PierreBrisorgueil** [comment]
> there have been reports of vue-cli 4 not working with sass-loader version 8.0.0. do you have it installed in your project? Try downgrading to sass-loader@7.3.1 should work.

Hello :) 

[fixed](https://github.com/vuejs/vue-cli/issues/4513) since rc.3, I'm un rc.7 everything is ok with rc.7 and sass-loader 8.0.0 before release 1.0.1

**Comment by ztoben** [comment]
I can replicate on my setup as well. This does not seem to be a vue-cli or sass-loader issue. Running vue-cli@rc.7 and sass-loader@8.0.0 works with this plugin on v1.0.0, but not v1.0.1

**Comment by DRoet** [comment]
@johnleider 

both `@vue/cli` `^3.12.0` and `^4.0.0-rc7` work with `sass-loader`: `8.0.0`, however the cli-plugin doesn't seem to support it (yet).

might be caused by:
https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/master/util/helpers.js#L49

that should probably be changed to `opts.prependData`

**Comment by bromix** [comment]
same here :( sticking with sass-loader v7.3.1 for long as this works all together.

**Comment by willemavjc** [comment]
@bromix @claudio10 For my personal knowledge, how do you achieve that? I mean, how do you get that particular version 7.3.1 of sass-loader rather than the 8.0.0?

```
yarn add @vue/cli@3.12.0
vue create .
vue add vuetify@1.0.0 #This still complains of sass-loader
```

**Comment by kdaghari** [comment]
@willemavjc here’s what you need to do:
(I’m assuming you’re doing a fresh install)
1. Go to the package.json file
2.
```javascript
// package.json
// ...
// Change this:
“sass-loader”: “^8.0.0”
// To this:
“sass-loader”: “^7.3.1”
```
3. ˋvue add vuetify`

**Comment by kdaghari** [comment]
@willemavjc here’s what you need to do:
(I’m assuming you’re doing a fresh install)

1. Go to the `package.json` file
2.
```javascript
// package.json
// ...
// Change this:
“sass-loader”: "^8.0.0"
// To this:
“sass-loader”: "^7.3.1"
```
3. `vue add vuetify`

**Comment by claudio10** [comment]
Just to complete information posted by @kdaghari for NPM: with NPM you simply do an installation adding a at-sign, just like:

npm -i -D sass-loader@7.3.1

**Comment by bromix** [comment]
> @bromix @claudio10 For my personal knowledge, how do you achieve that? I mean, how do you get that particular version 7.3.1 of sass-loader rather than the 8.0.0?
> 
> ```
> yarn add @vue/cli@3.12.0
> vue create .
> vue add vuetify@1.0.0 #This still complains of sass-loader
> ```
> 
> Do you do some manual import and then package.json editing?

Just remove the "^" and set the version fix in the package. Same like pip (requirements in python)

```
"sass-loader": "7.3.1",
```

For updating dependencies I only use "ncu" because npm won't update major updates.

**Comment by DRoet** [comment]
Please try the latest release `1.0.2`

**Comment by bromix** [comment]
> Please try the latest release `1.0.2`

It's working :D Thanks.

**Comment by d3radicated** [comment]
Confirmed working on `1.0.2`. Issue can be closed.

**Comment by PierreBrisorgueil** [comment]
Perfect, thx a lot :) !

**Comment by willemavjc** [comment]
Not working with `1.0.2` on my end.

Some file seems to be now missing:

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ~vuetify/src/styles/styles.sass.
        on line 1 of /home/node/app/src/components/HelloWorld.vue
>> @import '~vuetify/src/styles/styles.sass';
```

Scenario tested implies Docker and is as such:
```
docker image pull node:12.11.1-alpine
docker container run -d -p 8081:8080 [...] -it node:12.11.1-alpine sh
cd ~
yarn add @vue/cli@3.12.0
ln -s ~/node_modules/@vue/cli/bin/vue.js ~/.yarn/bin/vue
export PATH=${PATH}:~/.yarn/bin
cd ~/app
vue  create .
vue  add vuetify@1.0.2
yarn serve
```

**Comment by DRoet** [comment]
this is a different bug, if you specify the version number in `vue add`, the plugin is not being invoked.

> docker image pull node:12.11.1-alpine
> docker container run -d -p 8081:8080 [...] -it node:12.11.1-alpine sh
> cd ~
> yarn add @vue/cli@3.12.0
> ln -s \~/node_modules/@vue/cli/bin/vue.js \~/.yarn/bin/vue
> export PATH=${PATH}:~/.yarn/bin
> cd ~/app
> vue  create .
> vue  add vuetify@1.0.2
> yarn serve
> ```

make sure you do:
```sh
vue  create .
vue  add vuetify@1.0.2
vue  invoke vuetify
yarn serve
```

**Comment by willemavjc** [comment]
@droet Thanks. Confirmed working with vue/cli@3.12.0 ...and not working with @4.0.3, with the same error you mentioned in the new issue #4700 on Vue.js GitHub.

**Comment by willemavjc** [comment]
Would someone be able to clarify if the following warning is a real issue?

```
Plugin vue-cli-plugin-vuetify@1.0.2 does not have a generator to invoke
Choose a preset: Default (recommended)
WARN  conflicting versions for project dependency "sass-loader":

- ^8.0.0 injected by generator "undefined"
- ^7.1.0 injected by generator "vue-cli-plugin-vuetify"

Using newer version (^8.0.0), but this may cause build errors.
```

In package.json I can see this:
```
    "node-sass": "^4.12.0",
...
    "sass": "^1.17.4",
    "sass-loader": "^8.0.0",
```

I don't really understand what is happening and does it really imply.

**Comment by DRoet** [comment]
It shouldn't be an issue if your package.json has 8.0.0, see https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/123.
Also you shouldn't both use `node-sass` and `sass`, just using `sass` is enough

**Comment by willemavjc** [comment]
> Also you shouldn't both use `node-sass` and `sass`, just using `sass` is enough

Coming back to this interesting remark:
Does it mean I should not select CSS pre-processors when building a new project via Vue CLI? (I never changed anything in the package.json so I assume Vue CLI and Vuetify did it.)

**Comment by DRoet** [comment]
you should select is, but there are two options in the cli `dart-sass` or `node-sass`. you should always pick `dart-sass` for vuetify. `dart-sass === sass`

**Comment by CumpsD** [comment]
sass-loader 9.0.0 broke it again btw

```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
```

**Comment by DRoet** [comment]
@CumpsD https://github.com/vuetifyjs/vue-cli-plugins/pull/185

**Comment by CumpsD** [comment]
> @CumpsD #185

Thanks!
