### ISSUE TITLE
Update to 1.0.1 breaks build with variables.sass - variables are undefined

### ISSUE THREAD

**Issue by bromix** [vuetifyjs/vue-cli-plugin-vuetify#120]
I updated a couple of days back to version 1.0.0 and everything worked fine (even with the changes of variables.sass). Today I tried 1.0.1 and errors while building. Variables are suddenly undefined.

```
@ multi ./src/main.ts

 error  in ./node_modules/vuetify/src/components/VDataTable/VVirtualTable.sass

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  $material-light,
 ^
      Undefined variable.
   ╷
13 │   $material-light,
   │   ^^^^^^^^^^^^^^^
   ╵
  src\sass\variables.scss 13:3  @import
  stdin 1:9                     root stylesheet
```

[error.log](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/files/3711092/error.log)

**Comment by bromix** [comment]
Additional Info: I need to import the styles again....

```
@import '~vuetify/src/styles/styles.sass';
```

**Comment by VesterDe** [comment]
Happens to me as well. Solved by importing again also.

**Comment by MrJmpl3** [comment]
Depend if you use the default value of import from the vuetify-plugin , the vuetify plugin inject the `@import "~vuetify/src/styles/styles";` after your styles, the order is

- Your variables (not lists or maps) - variables.scss
- @import "~vuetify/src/styles/styles";
- Your variables (lists or maps) - lists.scss

https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/f0864903d9d4b474e922a3b8e0aef8ddeb1562be/util/helpers.js#L45

**Comment by bromix** [comment]
> Depend if you use the default value of import from the vuetify-plugin , the vuetify plugin inject the `@import "~vuetify/src/styles/styles";` after your styles, the order is
> 
> * Your variables (not lists or maps) - variables.scss
> * @import "~vuetify/src/styles/styles";
> * Your variables (lists or maps) - lists.scss
> 
> https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/f0864903d9d4b474e922a3b8e0aef8ddeb1562be/util/helpers.js#L45

I see. I added a lists.scss, moved the merge stuff from variables.scss in there and removed the import of the style. Now it works. So the documentation isn't up to date?

**Comment by DRoet** [comment]
I can't reproduce this using the latest vuetify (`2.1.4`) + cli-plugin (`1.0.2`) + @vue/cli (`3.12.0` or `4.0.2`)

Would be awesome if anyone can provide a barebones repository

**Comment by CesarGomezTissini** [comment]
The issue occurs mostly with Vuetify 1.5.17 and v1.0.1 for plugin.

**Comment by DRoet** [comment]
@CesarGomezTissini can't reproduce it either when using `1.5.17` altho I would probably recommend by using `vue-cli-plugin-vuetify@0.5.0` if you are still using v1

**Comment by DRoet** [comment]
I'm not sure which sass/scss rules you are referring to, vuetify 1.5 uses the older stylus setup: https://v15.vuetifyjs.com/en/framework/theme#modifying-stylus-variables

**Comment by CesarGomezTissini** [comment]
Referring to [https://vuetifyjs.com/en/getting-started/quick-start#vue-cli-3]this

**Comment by DRoet** [comment]
That doesn't apply when using `1.5`. either upgrade or refer to the [1.5 documentation](https://v15.vuetifyjs.com/en/getting-started/quick-start)

**Comment by johnleider** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [ ] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
