### ISSUE TITLE
[Bug Report] Error on building vue cli 3

### ISSUE THREAD

**Issue by Funkhero** [vuetifyjs/vue-cli-plugin-vuetify#124]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Linux x86_64

### Steps to reproduce
install vue cli 3
create new project
run "vue add vuetify"
run "npm run serve"
then 

### Expected Behavior

working project

### Actual Behavior
Error on each building module sass

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by below-1** [comment]
Seems like there is conflict between sass-loader added by vue-cli and vuetify .Creating the project without sass and then `vue add vuetify` work for me.

**Comment by DRoet** [comment]
Please try the latest release `1.0.2`

**Comment by willemavjc** [comment]
@Funkhero Are you experiencing errors like the one mentioned here: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/119#issuecomment-543064666 ?

**Comment by DRoet** [comment]
@willemavjc see https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/119#issuecomment-543071642

**Comment by willemavjc** [comment]
Thanks. Confirmed working. (This issue may be closed.)
