### ISSUE TITLE
Plugin overwrites SASS prependData project configuration

### ISSUE THREAD

**Issue by Lanchi** [vuetifyjs/vue-cli-plugin-vuetify#128]
Inside `vue.config.js` I have `css.loaderOptions` option defined as following:
```
css: {
    loaderOptions: {
      sass: {
        prependData: `@import "~@/styles/_mixins.scss"`,
      },
      scss: {
        prependData: `@import "~@/styles/_mixins.scss";`,
      }
    },
},
```
This is [official recommendation](https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders) for passing options to pre-processor loaders, instead of using `chainWebpack`.

However, Vuetify cli plugin is using `chainWebpack` and overwrites the user defined configuration. I placed logs for `opt.prependData` before and after line 56 in [util/helpers](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/master/util/helpers.js#L56) and here's what I get:

```
BEFORE @import "~@/styles/_mixins.scss";
AFTER @import '@/styles/variables.scss';
@import '~vuetify/src/styles/styles.sass';
```
Vuetify plugin should concatenate it's imports to the existing ones, or not use `chainWebpack` but the recommended way of defining these options.

Vue CLI service: `4.0.3`
Vuetify: `2.1.4`
Vue CLI plugin Vuetify: `1.0.2`

**Comment by DRoet** [comment]
Are you suggesting we just do `opt.prependData += data.join('\n')` instead?

feel free to PR it

**Comment by Lanchi** [comment]
> Are you suggesting we just do opt.prependData += data.join('\n') instead?

Something along those lines.

> feel free to PR it

Will do.
