### ISSUE TITLE
Only 'Default' preset generates a usable result

### ISSUE THREAD

**Issue by julijane** [vuetifyjs/vue-cli-plugin-vuetify#129]
I created a vue project using current @vue/cli package, then proceeded with `vue add vuetify`. When using the "Default" preset, the result works/looks fine. When using the "Prototype" or "Configure" preset, the end result fails with:

```
warning  in ./src/plugins/vuetify.js
"export 'default' (imported as 'Vuetify') was not found in 'vuetify'
```

Or to be specific: It does not fail, but then a (visually) empty page seems to be served.

I compared the output of Default preset and the other presets and found that one difference is that the Default preset in src/plugins/vuetify.js does

```
import Vuetify from 'vuetify/lib';
```

and the other presets do

```
import Vuetify from 'vuetify';
```

Changing this made the warning go away, but when then opening up the page one gets a unstyled mess, so it still does not yield a working result. From here I could not determine what to change furthermore to get a proper starting result.

**Comment by gwh-cpnet** [comment]
I think it is related to @vue/cli v4 which is released lately.

**Comment by gwh-cpnet** [comment]
if you scaffolld with @vue/cli v4, and you found 

```
transpileDependencies: [
     'vuetify',
],
```
in your `vue.config.js`, delete this section, it would work fine by then.
