### ISSUE TITLE
a la carte mode dont load components

### ISSUE THREAD

**Issue by edarblanco** [vuetifyjs/vue-cli-plugin-vuetify#13]
Uncaught TypeError: Cannot read property 'install' of undefined, is the error message that eslint throws, according to I read in [3496](https://github.com/vuetifyjs/vuetify/issues/3496), it corrects my problem halfway, since it is possible to use vuetify, but not its components

**Comment by WitteStier** [comment]
I can confirm the error `Uncaught TypeError: Cannot read property 'install' of undefined`.

**Comment by andrewharvey** [comment]
Does anyone know how to fix this or a workaround?

**Comment by edarblanco** [comment]
In itself, it is not vuetify itself, because if you use the old interface, vue init vuetifyjs/a-la-carte, everything works perfectly

**Comment by KaelWD** [comment]
Yeah sorry, I thought I'd posted a comment to go with that. It usually helps if you say what version of everything you're using, and the exact steps you took to reproduce the issue.

**Comment by edarblanco** [comment]
First create app (vue create test), then add vuetify plugin (vue add vuetify) and run app (yarn serve)
OS: Archlinux
Node: 10.3
vue-cli: 3.0.0-beta.15
vue-cli-plugin-vuetify: 0.13

**Comment by KaelWD** [comment]
Duplicate of #12
