### ISSUE TITLE
Minor: WARN npm npm does not support Node.js v13.0.0

### ISSUE THREAD

**Issue by willemavjc** [vuetifyjs/vue-cli-plugin-vuetify#132]
This is a minor issue but I think taking care of it may improve developer experience. 
So here it is:

The way the plugin checks for Node.js version is not correct as it comes to assume that a higher version is a lower one. A warning for possible no support of a newer version seems fine to me but the warning is quite confusing.

How it happens:
```
vue add vuetify@1.1.1
vue invoke vuetify
```

```
[...]
Plugin vue-cli-plugin-vuetify@1.1.1 does not have a generator to invoke
Choose a preset: Default (recommended)

Invoking generator for vue-cli-plugin-vuetify.
Installing additional dependencies.

yarn install v1.19.1
[...]
success Saved lockfile.
Done in 36.43s.

Running completion hooks...npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
```

The thing is, as stated, the Node.js is 13.0.0 so already newer than the others.
Perhaps a single message stating a "WARN - Only the versions x, y, z of Node.js are certified supported" would be sufficient.

Any point of view is welcomed.

**Comment by DRoet** [comment]
its an upstream issue in node, see https://github.com/nodejs/node/issues/30066. either upgrade to 13.0.1 or ignore the warning
