### ISSUE TITLE
[Bug Report] 30 seconds to compile with vuetify - bundle bigger than 1 MiB?

### ISSUE THREAD

**Issue by swinadeor** [vuetifyjs/vue-cli-plugin-vuetify#133]
### Environment
**Vuetify Version:** 2.1.6
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Mac OS 10.14.4

### Steps to reproduce
I'm currently trying to set up a VueJS project with Vuetify. For that I'm using the vue-cli to create a new project and after that I added Vuetify also through the vue-cli (no matter what type of config).

Then I compile the project and I noticed it takes longer up to 30 seconds to compile. I couple of months I did the same and the compiling time took only around 3 seconds. I thought it would be because of setting in the config the "offline icons" but that didn't have any effect.

Has anyone encountered the same issue? Would that be even normal?

### Expected Behavior
I would except when downloading the code, when I compile it to be only a couple of seconds.

### Actual Behavior
The compiling time takes longer than 25 seconds

### Reproduction Link
<a href="https://github.com/swinadeor/test_vue_vuetify" target="_blank">https://github.com/swinadeor/test_vue_vuetify</a>

**Comment by marcpaskell** [comment]
@johnleider - this delay also kicks in when scss variables are changed - do you know if there is a temp solution for this as it slows development considerably. Thanks

**Comment by johnleider** [comment]
I'm updating the plugin to only setup the data option when variables are present. There is no temp solution for speeding up compile time when using variables as far as I'm aware but I'm always open to help.

**Comment by mattgreenfield** [comment]
I've updated to 2.0.2 and do not have a `src/sass/variables.s(a|c)ss` file. 
I'm still experiencing slow build times that I wasn't a month ago. 89422ms where it used to be 20356ms
I am loading my own variables file using `vue.config.js` and have a total of 42 components.
Any help would be much appreciated.

**Comment by bahablgn** [comment]
> I've updated to 2.0.2 and do not have a `src/sass/variables.s(a|c)ss` file.
> I'm still experiencing slow build times that I wasn't a month ago. 89422ms where it used to be 20356ms
> I am loading my own variables file using `vue.config.js` and have a total of 42 components.
> Any help would be much appreciated.

Did you solve the problem? I do not have a src/sass/variables.s(a|c)ss file and still getting slow compile time
