### ISSUE TITLE
why this happend?

### ISSUE THREAD

**Issue by Adamkaram** [vuetifyjs/vue-cli-plugin-vuetify#134]
�  Installing vue-cli-plugin-vuetify...

yarn add v1.16.0
error Could not open cafile: ENOENT: no such file or directory, open 'C:\xamp\htdocs\vue-comments-overlay\undefined'
[1/4] Resolving packages...
[2/4] Fetching packages...
[########################

**Comment by Adamkaram** [comment]
this my package.json
 "dependencies": {
    "ajax": "0.0.4",
    "bootstrap-sass": "^3.4.1",
    "bootstrap-vue": "^2.0.4",
    "core-js": "^2.6.5",
    "element-ui": "^2.4.5",
    "express": "^4.17.1",
    "http-serve": "^1.0.1",
    "jquery": "^3.4.1",
    "jsdom": "^15.2.0",
    "p-limit": "^2.2.1",
    "popper.js": "^1.16.0",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuetify": "^2.1.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-pwa": "^3.11.0",
    "@vue/cli-plugin-unit-mocha": "^3.11.0",
    "@vue/cli-service": "^3.11.0",
    "@vue/eslint-config-prettier": "^5.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.1",
    "babel-plugin-component": "^1.1.1",
    "chai": "^4.1.2",
    "css-loader": "^3.2.0",
    "deepmerge": "^4.2.2",
    "eslint": "^5.16.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-vue": "^5.0.0",
    "fibers": "^4.0.2",
    "grunt": "^1.0.4",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-uglify": "^4.0.1",
    "grunt-sass": "^3.1.0",
    "grunt-vue": "^0.1.5",
    "node-sass": "^4.12.0",
    "postcss-loader": "^3.0.0",
    "prettier": "^1.18.2",
    "sass": "^1.23.1",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-element": "^1.0.1",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.3.0"
  }

**Comment by nekosaur** [comment]
Please add information about the exact steps you took

**Comment by jacekkarczmarczyk** [comment]
This issue is being closed due to:

- [x] Reproduction environment not provided (inactivity for 14 days)
- [x] Requested information not provided (inactivity for 14 days)
- [ ] Violation of the [Code of Conduct](https://github.com/vuetifyjs/vuetify/blob/dev/CODE_OF_CONDUCT.md)

Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
