### ISSUE TITLE
[Bug Report] Plugin Does not work

### ISSUE THREAD

**Issue by RaccoonDev** [vuetifyjs/vue-cli-plugin-vuetify#147]
### Environment

**Browsers:** Chrome 79.0.3945.88
**OS:** Mac OS 10.15.1

### Steps to reproduce
just run "vue add vuetify"

### Expected Behavior
vuetify is installed

### Actual Behavior
Error: Cannot find module 'shelljs'

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
"vue-cli-plugin-vuetify": "^2.0.3-beta.2",

**Comment by murito** [comment]
I had the same behavior. 
As workaround, after install your project with:

`vue create project_name`

Install shelljs:

`npm i shelljs`

and then add vuetify

`vue add vuetify`

This work for me

**Comment by PixelThin** [comment]
I see the same behavior. This worked last night but now installing the plugin causes a "Cannot find module shelljs" error.

To duplicate:
1. vue create test
2. Select the bare-bones option
3. cd test
4. vue add vuetify
5. Observe the following error:

ERROR  Error: Cannot find module 'shelljs'
Require stack:
- /home/dbeck/temp/test/node_modules/vue-cli-plugin-vuetify/generator/index.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli-shared-utils/lib/module.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli-shared-utils/index.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/lib/add.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/bin/vue.js
Error: Cannot find module 'shelljs'
Require stack:
- /home/dbeck/temp/test/node_modules/vue-cli-plugin-vuetify/generator/index.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli-shared-utils/lib/module.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli-shared-utils/index.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/lib/invoke.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/lib/add.js
- /home/dbeck/.config/yarn/global/node_modules/@vue/cli/bin/vue.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/dbeck/temp/test/node_modules/vue-cli-plugin-vuetify/generator/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)

**Comment by johnleider** [comment]
Resolved. You should be able to to run `yarn add vue-cli-plugin-vuetify@latest`.
