### ISSUE TITLE
Cant install vuetify in a new default project

### ISSUE THREAD

**Issue by kakulukia** [vuetifyjs/vue-cli-plugin-vuetify#22]
It left me with broken vue files where template code got inserted between the script and style sections.

plugin 0.1.6
vue cli: rc3

This was inserted between the tags in Home.vue

    l>
                <em>&mdash;John Johnson</em>
                </small>
            </footer>
            </blockquote>
        </v-layout>
        </v-slide-y-transition>
    </v-container>
    </template>

**Comment by skapator** [comment]
Same issue.
Maybe the vue-cli generator api's render method ?

When the source is a directory path it renders fine. But when it is an object it renders these artefacts.

```
  api.render('./templates/default', {
    ...opts,
  })
```
```
    const files = {
      './src/App.vue': './templates/default/src/App.vue',
      './src/assets/logo.png': './templates/default/src/assets/logo.png'
    }
    api.render(files, opts)
```
