### ISSUE TITLE
template string bug when running eslint - missing variable definition ?

### ISSUE THREAD

**Issue by didymu5** [vuetifyjs/vue-cli-plugin-vuetify#24]
I found this linting error when I added vuetify as a plugin:

error: Unexpected template string expression (no-template-curly-in-string) at babel.config.js:15:22:
  13 |       {
  14 |         vuetify: {
> 15 |           transform: 'vuetify/es5/components/${member}',
     |                      ^
  16 |           preventFullImport: true,
  17 |         },
  18 |       },
should I be ignoring the babel.config.js

johnleider - Today at 2:24 PM
oh um, that seems like a bug
looks like https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/dev/generator/index.js#L126 needs to be updated

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/guides/a-la-carte#importing-components

Reopen if I'm wrong and it's a bug anyway

**Comment by iancrowther** [comment]
I added the following rule to my .eslintrc.js

```
rules: {
  'no-template-curly-in-string': process.env.NODE_ENV === 'production' ? 'error' : 'off'
},
```

**Comment by jacekkarczmarczyk** [comment]
will be fixed in next release https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/28/commits/e51f930230adf64ffec442b6a7af08d093e30f8e
