### ISSUE TITLE
[Bug Report] Material Icons can't be loaded in bundled electron projects

### ISSUE THREAD

**Issue by timoschwarzer** [vuetifyjs/vue-cli-plugin-vuetify#31]
### Versions and Environment
**Vuetify:** 1.1.12
**Vue:** 2.5.17
**Browsers:** Other
**OS:** Linux x86_64

### Steps to reproduce
On Linux:

``` bash
vue create test
cd test
vue add electron-builder
vue add vuetify
yarn serve:electron # Material icons work
yarn build:electron
./dist_electron/test-0.1.0-x86_64.AppImage # Material icons don't work
```

### Expected Behavior
Font files should be properly placed and loaded in bundled electron projects.

### Actual Behavior
The icon font files are placed in `dist_electron/`. The CSS files are placed in `dist_electon/css` but the icons get referenced with `url(blablabla.ttf)` etc. so that electron searches for the font files in the css directory.

**Comment by jacekkarczmarczyk** [comment]
Following your steps I got working application, also font files are located in css folder
![image](https://user-images.githubusercontent.com/15625235/44228692-315aca00-a196-11e8-9f79-2ec9d2210a37.png)
Also you're experiencing the bug it seems that it's rather electron-builder responsibility

**Comment by timoschwarzer** [comment]
There's been an update to Vue CLI 2 hours ago and it works with that version. The version before that doesn't work. Nevertheless, thanks for your time! :)
