### ISSUE TITLE
Update to vuetify 1.1.14

### ISSUE THREAD

**Issue by urbgimtam** [vuetifyjs/vue-cli-plugin-vuetify#35]
Any change the plugin gets updated to the latest version of Vuetify?
This plugin is really handy, specially with the new Vue UI project management plugins. 
Or how can we update it manually?

**Comment by jacekkarczmarczyk** [comment]
It will be updated after releasing Vuetify 1.2

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
