### ISSUE TITLE
Issue with template created by the plugin

### ISSUE THREAD

**Issue by cfjedimaster** [vuetifyjs/vue-cli-plugin-vuetify#36]
This is probably minor, but I noticed it right away. I just created a new Vue app, added the Vuetify plugin, and let it update my default components with it's sample code. On initial load, you get this:

![image](https://user-images.githubusercontent.com/393660/44486875-69d92880-a61a-11e8-8f84-e47914c39006.png)

If you click the hamburger menu on the right to open the panel, then click "Switch drawer", you get this:

![image](https://user-images.githubusercontent.com/393660/44486912-82e1d980-a61a-11e8-9e76-67b5b12d8832.png)

If you then dismiss the panel, you get this:

![image](https://user-images.githubusercontent.com/393660/44486929-8d03d800-a61a-11e8-97c3-40b974870a24.png)

Note the header is now partially hidden behind the initial left panel. At that point, there doesn't seem to be a way to fix it.

**Comment by jacekkarczmarczyk** [comment]
Template has been changed
https://github.com/vuetifyjs/vue-cli-plugin-vuetify/commit/0c104634e5dc8eb470333e9f5e7cd94213273b7f
