### ISSUE TITLE
how to debug my ower plugin?

### ISSUE THREAD

**Issue by lefreet** [vuetifyjs/vue-cli-plugin-vuetify#37]
hello, i'm trying to develop a plugin for vue cli 3.0 ;  

but in my development environmen, it seem have no way to debug my plugin code， i only find the command of `invoke`；

Could you tell my some method or flows to develop a cli plugin ? thanks

Forgive me for my poor English

**Comment by jacekkarczmarczyk** [comment]
Please ask in vue-cli repository
