### ISSUE TITLE
[Bug Report] Installation fails when src directory is not found

### ISSUE THREAD

**Issue by Uninen** [vuetifyjs/vue-cli-plugin-vuetify#39]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.92
**OS:** Mac OS 10.13.5

### Steps to reproduce
I tried to install Vuetify in a project where the 'src' directory has been renamed to 'vue' and the installation fails when running completion hooks: "Error: ENOENT: no such file or directory, open '/code/src/main.js'"

### Expected Behavior
I'm not sure if it's reasonable to expect people to move things around, but at least the installer could just fail gracefully and either ask for the new directory name or just say that "didn't find src directory in default place, skipped writing of pre-made templates".

### Actual Behavior
Error: ENOENT: no such file or directory, open '/code/src/main.js'

### Reproduction Link
[https://codesandbox.io/s/z21zlv53jx](https://codesandbox.io/s/z21zlv53jx)

**Comment by eder-toledo** [comment]
My error has a relationship?

### **Versions and Environment**

babel/polyfill: 7.0.0-rc.1
vue: 2.5.17
vuetify: 1.2.0
OS: Windows 10

### **Steps to reproduce**
Quick start: https://vuetifyjs.com/en/getting-started/quick-start
in the step: npm run serve

### **Actual Behavior**

Error: Failed to compile with 1 errors
![imagen](https://user-images.githubusercontent.com/2104229/45760141-05948f00-bbef-11e8-89d2-37bd76787f3a.png)

**Comment by jacekkarczmarczyk** [comment]
@eder-toledo not enough information in your comment to say anything about your issue - i don't know what did you do before running `serve`, i don't see what error is thrown. Please create a separate issue with proper reproduction

**Comment by jacekkarczmarczyk** [comment]
@Uninen can you reproduce your issue with 0.2.0 version of vuetify plugin? I think it could handle the entry file properly, the problem with the location of components may still exist though

**Comment by Uninen** [comment]
My reported versions were wrong as I either read them wrong or vue-cli does some magic with them; used most recent versions (as of couple of days ago) of everything.

I created a clean project to reproduce this ( https://gitlab.com/uninen/vuetify-cli-bug ) and the installer didn't fail but instead wrote everything in src directory (it may have failed in my other project because I have src dir there for other stuff). I think this is semi-OK as it can't know better. I only opened this ticket because the installer crashed and this seems not to be the case; feel free to close this ticket.

**Comment by jacekkarczmarczyk** [comment]
The plugin was updated just after you've reported the issue, and in 0.2.0 we've improved the way of resolving the entry file.
I think it will be safe to save the template files in the same folder as the entry file instead of fixed `/src`

**Comment by Uninen** [comment]
Hmm. with the repo above (where entry file points to `vue/main.js`) this 0.2.0 plugin still wrote the templates in `src` folder. (I added each steps as separate commits, should be easy enough to repro.)

But yes, it's a fair assumption to write them in the same folder as the entry file.

**Comment by jacekkarczmarczyk** [comment]
Only resolving of the entry file has been fixed, templates are still being saved in the `src`, this needs to be fixed as well, that's why I'm not closing the issue

**Comment by jacekkarczmarczyk** [comment]
@Uninen I didn't look into your repro before, but I can see now that you're using vue cli 2.X in you project. In 3.0 changing the src folder is not so easy: https://github.com/vuejs/vue-cli/issues/1134#issuecomment-384856754 (and previous comments), and atm I'm not sure if we want to support 2.X

**Comment by Uninen** [comment]
The proper repro project is here, it's done with the latest cli v3: https://gitlab.com/uninen/vuetify-cli-bug

Everything else in the project works ok, but hadn't seen that "you're on your own" comment before -- this is clearly not documented. But feel free to close this ticket if it's out of scope (not officially supported by vue-cli) anyways.
