### ISSUE TITLE
Issue related to 'useBuiltIns' options.

### ISSUE THREAD

**Issue by SachinMaharana** [vuetifyjs/vue-cli-plugin-vuetify#44]
I created a vue project with vue create my-app and added vue add vuetify. But i am facing issue related to useBuiltIns options with error 

BABEL] /src/main.js: The 'useBuiltIns' option has been removed. The @babel/runtime module now uses builtins by default. (While processing: "base$0$7")

I have added the codesandbox here.

https://codesandbox.io/s/zxj5pkwzzl

Please help with this issue.

**Comment by johnleider** [comment]
I'm not sure what the exact issue is, but I can say it has nothing to do with Vuetify. <https://codesandbox.io/s/kkwyx3mm6v>
