### ISSUE TITLE
Plugin includes severely outdated materialdesign font

### ISSUE THREAD

**Issue by Sumurai8** [vuetifyjs/vue-cli-plugin-vuetify#54]
**Reproduction**

```
> vue add vuetify

? Choose a preset: Configure (advanced)
? Use a pre-made template? (will replace App.vue and HelloWorld.vue) Yes
? Use custom theme? No
? Use custom properties (CSS variables)? No
? Select icon font Material Icons
? Use fonts as a dependency (for Electron or offline)? Yes
? Use a-la-carte components? Yes
? Select locale English
```

In the ` Use fonts as a dependency (for Electron or offline)` step, the plugin will include https://www.npmjs.com/package/material-design-icons-iconfont , which is severely outdated and does not seem actively maintained (https://github.com/jossef/material-design-icons-iconfont/issues). It should include a repository that is using the latest font version (https://fonts.googleapis.com/icon?family=Material+Icons), or remove the option altogether, because there are a **lot** of ligatures missing in the font file that is included.

**Comment by KaelWD** [comment]
That's google's fault, their repo isn't maintained either. `material-design-icons-iconfont` is just a fork without source files published on npm.

**Comment by johnleider** [comment]
I can understand your frustration but we are simply providing the latest available version that we have access to. If the other project becomes not maintained for an extended period we can consider removing the option, but for now, it stays.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
