### ISSUE TITLE
[Bug Report] vue-cli-plugin breaks babel

### ISSUE THREAD

**Issue by lol2x** [vuetifyjs/vue-cli-plugin-vuetify#55]
### Versions and Environment
**Vuetify:** 1.3.3
**Vue:** 2.5.17
**Browsers:** Chrome 70.0.3538.77
**OS:** Windows 10

### Steps to reproduce
Build project in modern mode 

### Expected Behavior
Legacy mode should be transpilled corectlly

### Actual Behavior
Legacy file is not transpilled with babel

### Reproduction Link
[https://github.com/lol2x/TestModernLegacy](https://github.com/lol2x/TestModernLegacy)

**Comment by KaelWD** [comment]
`transpileDependencies: ['vuetify']` needs to be added to vue.config.js

**Comment by lol2x** [comment]
I believe this does not solve whole problem, for example after build check app-legacy.js it still has const store - which without vue-cli-plugin is transpilled to var.

**Comment by KaelWD** [comment]
https://caniuse.com/#feat=const

Legacy mode doesn't mean vuetify will magically start supporting IE10. Does the legacy build still work in IE11 with that change and --modern?

**Comment by lol2x** [comment]
Nope
![image](https://user-images.githubusercontent.com/6354070/47719018-28807d00-dc4a-11e8-8e67-8ff350c6a3db.png)

**Comment by lol2x** [comment]
Also what i mean about const is - if you will try my repo without vue-cli-plugin added (init commit) it transpiles const to var.

**Comment by lol2x** [comment]
I believe [index.js](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/7fef6454b8a2b7a6c6898b7264418e34539f424e/index.js#L10) lines 10-15 is the issue.

**Comment by albertlinga** [comment]
@KaelWD 

I modified vue.config.js to look like this 

module.exports = {
  transpileDependencies: ['babel-polyfill','vuetify']
}

But I'm getting errors now 

Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by albertlinga** [comment]
https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/58 approach of removing include in js rule fixed it for me but I didn't transpile my dependency. transpiliing dependency caused the issue above regarding mixing import and module.exports

**Comment by breadadams** [comment]
After spending a day investigating why half of my app had suddenly stopped transpiling correctly upon build I've managed to pinpoint the issue to a recent migration from vue-cli 2 → 3, and with so the use of the vuetify CLI plugin in favor of a "manual" setup (so to say).

The main issue was that spread operators were being left in-tact, and therefore causing `SCRIPT1028` errors in Edge/IE11, and `missing : after property id` in older versions of Firefox.

It would _seem_ the issue lies within `vuetify-loader` (added during `vue add vuetify` from the a-la-carte option). After removing the dependency everything's back to normal, although of course the bundle size is a few kb larger now.

Is that what #58 intends to resolve @albertlinga @aeby ? 🤔

**Comment by KaelWD** [comment]
`transpileDependencies` definitely works in some situations, I just haven't figured out what yet. I have an older vue-cli 3 using it no problem, but a brand new one will fail with `Cannot assign to read only property 'exports' of object '#<Object>'` for some reason. I've removed the `include` at least, so you'll just have to figure out your own polyfill solutions til we get the rest of it worked out.

**Comment by Aymkdn** [comment]
> I have an older vue-cli 3 using it no problem

Which version @KaelWD  ?

**Comment by Aymkdn** [comment]
I think I finally figured it out.

When you do `transpileDependencies: ['vuetify']`, then https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/index.js#L26 will search **vuetify** in the path, so if your project is called **test-vuetify** (as mine), then it will include **ALL** files causing multiple errors. Also, even if your folder or its parents don't have "vuetify", it will include any other node modules with that name (for example **vuetify-loader** and **vue-cli-plugin-vuetify**).

The solution is to use 

- `transpileDependencies: ['/vuetify/']` for MacOS/Linux
- or `transpileDependencies: ['\\vuetify\\']` for Windows,
- or a regexp that will work for both worlds like `transpileDependencies: [/(\/|\\)vuetify(\/|\\)/]`

I believe the [Vuetify documentation](https://vuetifyjs.com/en/getting-started/quick-start#ie11-support) must be updated to indicate we need to add the above `transpileDependencies` in `vue.config.js`. 

cc https://github.com/vuetifyjs/vuetify/issues/4997 and https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/58

**Comment by jacekkarczmarczyk** [comment]
Please create a new issues (or better PR). Thank you

**Comment by KaelWD** [comment]
That explains why none of my test projects worked even if I downgraded all the vue-cli plugins to match the working one. It's pretty retarded that it matches the full path. Simpler cross-platform regex is `[/[/\\]vuetify[/\\]/]`, feel free to PR that back to this plugin like #58 tried to do. Note that this should either be always applied, or the old babel-polyfill setup needs to be brought back for non-alacarte use.
