### ISSUE TITLE
workbox download font files which browser doesn't need

### ISSUE THREAD

**Issue by maxzhou0** [vuetifyjs/vue-cli-plugin-vuetify#61]
for example i use latest chrome version , it supports woff2. so it not necessary to download all other versions file(woff,eot and svg).
how to config it?

**Comment by jacekkarczmarczyk** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
