### ISSUE TITLE
No such file or directory, open './public/index.html'

### ISSUE THREAD

**Issue by florianrusch** [vuetifyjs/vue-cli-plugin-vuetify#65]
If I'm trying to add vuetify with the command `vue add vuetify` I'm getting the following error:

```shell
$ vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@0.4.6
added 1 package from 1 contributor and audited 11862 packages in 6.828s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
📦  Installing additional dependencies...

added 11 packages from 49 contributors and audited 11898 packages in 8.375s
found 0 vulnerabilities

⠋  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open '<PROJECT PATH>/public/index.html'
Error: ENOENT: no such file or directory, open '<PROJECT PATH>/public/index.html'
    at Object.openSync (fs.js:451:3)
    at Object.writeFileSync (fs.js:1213:35)
    at Object.updateFile (<PROJECT PATH>/node_modules/vue-cli-plugin-vuetify/generator/tools/helpers.js:43:6)
    at Object.addLinks (<PROJECT PATH>/node_modules/vue-cli-plugin-vuetify/generator/tools/fonts.js:59:11)
    at api.onCreateComplete (<PROJECT PATH>/node_modules/vue-cli-plugin-vuetify/generator/index.js:34:33)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:143:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I don't have a `public` folder in my project folder. I don't know if there changes something in vue (I'm just started with vue). If I'm creating the file `public/index.html` and run the command again, there will be two lines added into the file:

```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons">
```

I'm running on vue 2.5.17.

**Comment by jacekkarczmarczyk** [comment]
Did you create your project with vue-cli 3?

**Comment by florianrusch** [comment]
@jacekkarczmarczyk yes. I'm currently using vue-cli 3.0.5

**Comment by jacekkarczmarczyk** [comment]
No, it would be a problem if you didn't create it with vue cli 3. But I think that cli creates public/index.html by default, so I don't know why you don't have this file.
Anyway I'm closing the issue for now, but if you can provide reproduction steps that produce the project without public/index.html (other then removing/moving them manually) feel free to show it here, we'll try to investigate

**Comment by CavalcanteLeo** [comment]
same here

**Comment by jacekkarczmarczyk** [comment]
@CavalcanteLeo there are thousands of things that could have happen BEFORE you run `vue add vuetify` so I need to have full reproduction steps including the project creation, not just adding the plugin

**Comment by andre-filho** [comment]
I think I know what is happening:

When you create your project using `vue create <project>` the CLI creates the **public/index.html** file. So `vue add vuetify` finds it and works nicely.

But when a project is created using `vue init <template> <project>` with a common template like webpack, a **public/index.html** file is not actually created, instead a **index.html** file is created at project's root dir. Therefore during the plugin installation the target folder isn't found and we get that error.

So, to reproduce our error:
1. Create a project with the `vue init webpack <project>`
2. Run `vue add vuetify`
3. Choose plugin configuration
4. See error

**Comment by jacekkarczmarczyk** [comment]
So that's not a bug, plugin is intended to work only with projects created with `vue cli 3`'s `vue create <project>`

**Comment by dhust** [comment]
So does this mean we can't use vuetify during development if we use webpack?

**Comment by jacekkarczmarczyk** [comment]
No, it means that if you want to use vuetify plugin you need to use vue cli 3. If you don't use vue cli then you need to add vuetify manually https://vuetifyjs.com/en/getting-started/quick-start#existing-applications
