### ISSUE TITLE
`vue add vuetify` clobbers App.vue, without warning

### ISSUE THREAD

**Issue by iyerusad** [vuetifyjs/vue-cli-plugin-vuetify#74]
`vue add vuetify` will clobber existing App.vue, without warning.  

Not the end of the world, especially if you are using source control/backups as the readme directs you to, but still, not the best behavior (imagine if installing dropbox clobbered your Documents folder).

**Suggestion on how to address:**
**A)** Include warnings if intending to clobber/overwrite existing files
     This is decidedly a courtesy, one that exists in some places and not in others, e.g. `rm -rf / ` won't necessarily warn, but many applications will extend that courtesy. 

**B)** Copy/move any files intending to overwrite

**C)** Default to recommending `npm add vuetify` in readme and on the Vuetify quickstart page.
The behavior of `vue add vuetify` is bit of misnomer (`vue add vuetify` is closer to replace or reconfigure behavior).

**Comment by LinusBorg** [comment]
This is from our Vue CLI  3 docs:

> WARNING
> 
> It is recommended to commit your project's current state before running vue add, since the command will invoke the plugin's file generator and potentially make changes to your existing files.

But of course not everyone reads/finds that warning. 

So we plan to giove a warning before invoking a generator if a projects either has uncommitted changes or doesn't have a repository:

https://github.com/vuejs/vue-cli/issues/3250

I don't think that warnings like this should be added to individual plugins, as this is a general behjaviour of pugin generators.

**Comment by iyerusad** [comment]
Agreed. Closing in favor of https://github.com/vuejs/vue-cli/issues/3250

Thanks @LinusBorg
