### ISSUE TITLE
[Bug Report] Error on install

### ISSUE THREAD

**Issue by pierrejoye** [vuetifyjs/vue-cli-plugin-vuetify#84]
### Versions and Environment
**Vuetify:** 1.5.4
**Last working version:** 1.5.4
**Vue:** 2.6.8
**Browsers:** Chrome 72.0.3626.119
**OS:** Linux x86_64

### Steps to reproduce
vue add vuetify
or 
vue add vue-cli-plugin-vuetify

vue add vuetify tries to add vue-clie-plugin-vuetify but fails on installing it. Missing logo.svg file.

### Expected Behavior
installs either package

### Actual Behavior
```
pierre@pierre-xps:~/project/heroleads/src/alpha-frontend$ vue add vue-cli-plugin-vuetify

📦  Installing vue-cli-plugin-vuetify...

yarn add v1.12.1
[1/5] Resolving packages...
[2/5] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[5/5] Cleaning modules...
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-vuetify@0.4.6
info All dependencies
└─ vue-cli-plugin-vuetify@0.4.6
Done in 5.25s.
✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
 ERROR  Error: ENOENT: no such file or directory, open '/home/pierre/project/heroleads/src/alpha-frontend/node_modules/vue-cli-plugin-vuetify/generator/templates/default/src/assets/logo.svg'
Error: ENOENT: no such file or directory, open '/home/pierre/project/heroleads/src/alpha-frontend/node_modules/vue-cli-plugin-vuetify/generator/templates/default/src/assets/logo.svg'
    at Object.fs.openSync (fs.js:646:18)
    at Function.module.exports.sync (/usr/local/share/.config/yarn/global/node_modules/isbinaryfile/index.js:117:25)
    at renderFile (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:301:16)
    at _injectFileMiddleware.files (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/GeneratorAPI.js:196:27)
    at Generator.resolveFiles (/usr/local/share/.config/yarn/global/node_modules/@vue/cli/lib/Generator.js:200:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### Other comments
No link as it is an install issue

**Comment by pierrejoye** [comment]
Interestingly enough I cannot reproduce on the same vue project but without having buefy installed. I am still not sure why this file does not get installed but it looks like it is not a vuetify issue but yarn/npm. thoughts?

**Comment by baermathias** [comment]
Getting a similar error:

```
vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

audited 23795 packages in 6.999s
found 0 vulnerabilities

✔  Successfully installed plugin: vue-cli-plugin-vuetify

Plugin vue-cli-plugin-vuetify does not have a generator to invoke
```

When installing it via vue ui, getting:
`No prompts found for vue-cli-plugin-vuetify`

an then it hangs forever on:
`Invoking vue-cli-plugin-vuetify...`

**Comment by johnleider** [comment]
Is this still occurring? Given the error and the fact that the file is there, I'm not sure why it's barking. @baermathias Please create a new issue as that is completely different.

**Comment by pierrejoye** [comment]
Just for the record, I could not repro it with latest packages. however it happened while having buefy first installed and then it fails with this error on vuetify. So should work but make little sense to have the two together (was using this simple project to report other issues:)

anyway, not a vuetify problem per se.

**Comment by KaelWD** [comment]
We can't promise compatibility with every plugin, especially other component libraries. That error is pretty weird though as it's saying a file in node_modules isn't found, can you verify that it's actually present on disk? This may be a vue-cli problem.

**Comment by pierrejoye** [comment]
@kaelwd in my case, the file was present on disk.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
