### ISSUE TITLE
[Bug Report] 'vue add vuetify' returning 404 

### ISSUE THREAD

**Issue by RichardCr** [vuetifyjs/vue-cli-plugin-vuetify#88]
### Versions and Environment
**Vuetify:** 1.5.7
**Vue:** 3.5.4
**Browsers:** Chrome 73.0.3683.75
**OS:** Linux x86_64

### Steps to reproduce
Install vue 3.5.4
Run: `vue add vuetify`

### Expected Behavior
Add Vuetify to my project

### Actual Behavior
Get:  
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-cli-plugin-vuteify - Not found
npm ERR! 404 
npm ERR! 404  'vue-cli-plugin-vuteify@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
```

**Comment by jacekkarczmarczyk** [comment]
`vue-cli-plugin-vuteify` => `vue-cli-plugin-vuetify`

**Comment by RichardCr** [comment]
:man_facepalming:

**Comment by Wollie333** [comment]
NOt sure how to fix this....also got this error exactly the same....

I am total noob just starting out...can someone help please

**Comment by Langdi** [comment]
> NOt sure how to fix this....also got this error exactly the same....
> 
> I am total noob just starting out...can someone help please

Most likely you made a spelling mistake.
