### ISSUE TITLE
Adding vuetify to cli project build error

### ISSUE THREAD

**Issue by beefsteak** [vuetifyjs/vue-cli-plugin-vuetify#89]
$ vue-cli-service serve --mode development --dashboard
 INFO  Starting development server...

Starting type checking and linting service...

  0% compilingUsing 1 worker with 2048MB memory limit

 91% recording DONE  Compiled successfully in 17043ms16:42:24

ERROR in D:/TLCodeOnline/beefsteak/TryOnce/TryOnce.Sale.WebSPA/node_modules/vuetify/types/alacarte.d.ts
8:12 Module '"../../../../../../../TLCodeOnline/beefsteak/TryOnce/TryOnce.Sale.WebSPA/types/vuetify"' has no exported member 'ComponentOrPack'.
     6 |
     7 | declare module 'vuetify/es5/components/*' {
  >  8 |   import { ComponentOrPack } from 'vuetify'
       |            ^
     9 |   import { VueConstructor } from 'vue'
    10 |
    11 |   const VuetifyComponent: {
ERROR in D:/TLCodeOnline/beefsteak/TryOnce/TryOnce.Sale.WebSPA/node_modules/vuetify/types/lib.d.ts
3:12 Module '"../../../../../../../TLCodeOnline/beefsteak/TryOnce/TryOnce.Sale.WebSPA/types/vuetify"' has no exported member 'Vuetify'.
    1 | declare module 'vuetify/lib' {
    2 |   import { Component, DirectiveOptions } from 'vue'
  > 3 |   import { Vuetify } from 'vuetify'
      |            ^
    4 |   import { Colors } from 'vuetify/lib/util/colors'
    5 |
    6 |   const Vuetify: Vuetify

No lint errors found
Version: typescript 3.4.4, tslint 5.16.0
Time: 4240ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.3.62:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

**Comment by KaelWD** [comment]
Is it a fresh project? Do you have any other plugins installed? What vue-cli and vuetify versions? What options did you select when creating the project? Have you read #43? What's your tsconfig?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
