### ISSUE TITLE
Unit test error

### ISSUE THREAD

**Issue by ImmortalDragonm** [vuetifyjs/vue-cli-plugin-vuetify#9]
@vue/cli: 3.0.0-beta.10
vue-cli-plugin-vuetify: 0.1.3
vuetify: 1.0.16

When i run unit test, i'v got this error message.

```
    console.error node_modules/vue/dist/vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    (found in <Root>)

    console.error node_modules/vue/dist/vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-slide-y-transition> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    (found in <Root>)

    console.error node_modules/vue/dist/vue.runtime.common.js:589
    [Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    (found in <Root>)
```

Step to reproduce:
  ```
vue create myapp
  cd myapp
  vue add vuetify
  npm run test:unit
```

**Comment by nekosaur** [comment]
Which options did you select when adding vuetify?

**Comment by ImmortalDragonm** [comment]
```
? Allow Vuetify to replace App.vue and HelloWorld.vue? Yes
? Use custom theme? No
? Use a-la-carte components? No
? Use babel/polyfill? Yes
```

**Comment by nekosaur** [comment]
I just realized that we don't actually try to modify test setup at all currently. It should probably be an option.

**Comment by ImmortalDragonm** [comment]
I know? that test don't modify, and add option - is good.
But what about warning? 
`[Vue warn]: Unknown custom element: <v-container> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
How to solve them?

**Comment by nekosaur** [comment]
It depends on what test framework you're using. You might have an entry point index.js for your tests where you can do `Vue.use(Vuetify)`. Basically you need to load the vuetify library when running your tests.

**Comment by ImmortalDragonm** [comment]
Where is no index.js in jest nor mocha+chai (options in vue create)

**Comment by eskemojoe007** [comment]
Running into a similar issue...any solution for `jest`?  I use the cli and am running into these issues.

**Comment by arafath-mk** [comment]
```
import { shallowMount } from '@vue/test-utils';
import HelloWorld from '@/components/HelloWorld.vue';
import Vue from 'vue';
import Vuetify from 'vuetify';

Vue.use(Vuetify);

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message';
    const wrapper = shallowMount(HelloWorld, {
      propsData: { msg },
    });
    expect(wrapper.text()).toMatch(msg);
  });
});  
```

**Comment by rustyx** [comment]
Create a file `tests/unit/index.js`:
```
import Vue from 'vue';
import Vuetify from 'vuetify';
Vue.config.productionTip = false;
Vue.use(Vuetify);
```

Then add to `jest.config.js`:
```
  setupFiles: [ '<rootDir>/tests/unit/index.js' ],
```

**Comment by johnleider** [comment]
There is now a section in the documentation dedicated towards explaining how to do this https://vuetifyjs.com/getting-started/unit-testing .

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
