### ISSUE TITLE
How to use Vuetify 2 beta version with this plugin?

### ISSUE THREAD

**Issue by mumairofficial** [vuetifyjs/vue-cli-plugin-vuetify#95]

**Comment by anderfernandes** [comment]
@mumairofficial I added the beta plugin to a fresh created vue-cli project and did vue add vuetify, just a little bit ago, and it worked for me. Good luck!

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
