### ISSUE TITLE
How to install older version, say 1.5.16?

### ISSUE THREAD

**Issue by davidhooey** [vuetifyjs/vue-cli-plugin-vuetify#99]
The `vue add vuetify` will install version `2.0.x`. Is there a way to install an older version of Vuetify?

**Comment by washyn** [comment]
I also try to do the same, I want to add an earlier version, but by default the most recent is installed, help please!!!

**Comment by jacekkarczmarczyk** [comment]
```bash
vue create v1
vue add vuetify@0.5
vue invoke vuetify
```

**Comment by washyn** [comment]
thank you very much it helped me a lot

**Comment by alexander-elgin** [comment]
> ```shell
> vue create v1
> cd v1
> vue add vuetify@0.5
> vue invoke vuetify
> ```

For me it does not install required dependencies e.g. stylus and stylus-loader
